<div class="presentation-shell">
    <div class="bg-gradient-to-r from-violet-950 to-violet-800 text-white px-6 sm:px-8 py-5 flex items-center justify-between gap-4 flex-wrap">
        <div>
            <p class="presentation-kicker text-violet-200 text-xs">Presentation</p>
            <h2 class="presentation-title text-3xl sm:text-4xl text-white mt-1">{{ $lesson?->title ?? 'Marksmanship Subject Overview' }}</h2>
        </div>
        <div class="text-xs text-violet-100 max-w-md">
            Use the arrows to move page by page. Scrolling is disabled in this shell.
        </div>
    </div>

    <div class="presentation-stage" id="presentation-stage">
        @php
            $lessonPages = $lessonPages ?? collect();
        @endphp

        <!-- Introduction Page -->
        <section class="presentation-page active" data-page="0" data-lesson="intro">
            <div class="presentation-content">
                <div class="flex flex-col justify-center items-center h-full px-6 sm:px-8 py-12">
                    <div class="max-w-2xl mx-auto text-left">
                        <p class="text-violet-600 text-sm font-semibold uppercase tracking-wide mb-3">Introduction</p>
                        <h1 class="text-5xl sm:text-6xl font-bold text-gray-900 mb-6">Gun Parts & Systems</h1>
                        <p class="text-xl text-gray-700 mb-8 leading-relaxed">
                            A comprehensive guide to understanding firearm components, weapon types, and identification of critical gun parts used across different weapon systems.
                        </p>
                        <div class="flex flex-col gap-4">
                            <p class="text-lg text-gray-600">This course covers:</p>
                            <ul class="space-y-3">
                                <li class="flex gap-3 items-center">
                                    <i class="fas fa-check text-violet-500"></i>
                                    <span class="text-gray-700">Firearm overview and safety concepts</span>
                                </li>
                                <li class="flex gap-3 items-center">
                                    <i class="fas fa-check text-violet-500"></i>
                                    <span class="text-gray-700">Weapon types and their characteristics</span>
                                </li>
                                <li class="flex gap-3 items-center">
                                    <i class="fas fa-check text-violet-500"></i>
                                    <span class="text-gray-700">Parts identification and functionality</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Lesson 1.1: Firearm Overview -->
        <section class="presentation-page" data-page="1" data-lesson="1.1">
            <div class="presentation-content">
                <div class="flex flex-col items-center h-full px-6 sm:px-8 py-12">
                    <div class="max-w-4xl w-full text-left">
                        <h2 class="text-4xl font-bold text-gray-900 mb-2">1.1 Firearm Overview</h2>
                        <div class="h-1 w-24 bg-violet-500 mb-8"></div>
                        
                        <div class="space-y-8 flex-grow">
                        <div>
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-gun text-violet-500"></i>
                                What is a Firearm?
                            </h3>
                            <p class="text-lg text-gray-700 leading-relaxed">
                                A firearm is a device designed to propel projectiles through a barrel using the force generated by a controlled explosion. Modern firearms are precision instruments used in law enforcement, military, and civilian applications.
                            </p>
                        </div>

                        <div>
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-shield-alt text-violet-500"></i>
                                General Safety Concept Overview
                            </h3>
                            <ul class="text-lg text-gray-700 space-y-3">
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span>Always treat every firearm as if it were loaded</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span>Keep the muzzle pointed in a safe direction</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span>Keep your finger off the trigger until ready</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span>Be aware of your target and surroundings</span>
                                </li>
                            </ul>
                        </div>

                        <div>
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-layer-group text-violet-500"></i>
                                Firearm Classification Basics
                            </h3>
                            <ul class="text-lg text-gray-700 space-y-3">
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span><strong>Pistols:</strong> Handheld firearms designed for one or two-handed operation</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span><strong>Rifles:</strong> Long-barreled firearms designed for accuracy at distance</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span><strong>Shotguns:</strong> Large-caliber weapons designed for spread ammunition</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Lesson 1.2: Weapon Types in System -->
        <section class="presentation-page" data-page="2" data-lesson="1.2">
            <div class="presentation-content">
                <div class="flex flex-col items-center h-full px-6 sm:px-8 py-12">
                    <div class="max-w-4xl w-full text-left">
                        <h2 class="text-4xl font-bold text-gray-900 mb-2">1.2 Weapon Types in System</h2>
                        <div class="h-1 w-24 bg-violet-500 mb-8"></div>
                        
                        <div class="space-y-10 flex-grow">
                        <!-- 9mm Pistol -->
                        <div class="border-l-4 border-violet-500 pl-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-3">• 9mm Pistol</h3>
                            <ul class="space-y-2 text-gray-700">
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Semi-automatic operation concept:</strong> Fires one round per trigger pull, automatically chambers the next round</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Magazine-fed system:</strong> Ammunition stored in removable magazines, typically 15-17 rounds</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Common use in law enforcement:</strong> Standard duty weapon for most police departments</span>
                                </li>
                            </ul>
                        </div>

                        <!-- .45 Caliber Pistol -->
                        <div class="border-l-4 border-violet-500 pl-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-3">• .45 Caliber Pistol</h3>
                            <ul class="space-y-2 text-gray-700">
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Larger caliber impact concept:</strong> Larger projectile (11.43mm) delivers more stopping power</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Semi-automatic mechanism:</strong> Same operational principle as 9mm but with enhanced power</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Recoil difference vs 9mm:</strong> Noticeably higher recoil impulse requires experienced handling</span>
                                </li>
                            </ul>
                        </div>

                        <!-- .38 Revolver -->
                        <div class="border-l-4 border-violet-500 pl-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-3">• .38 Revolver</h3>
                            <ul class="space-y-2 text-gray-700">
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Cylinder-based firing system:</strong> Ammunition held in rotating cylinder with typically 5-6 chambers</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Revolving mechanism:</strong> Cylinder rotates with each trigger pull to align next round</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Simplicity and reliability:</strong> Fewer moving parts make it extremely dependable</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Lesson 1.3: Parts Identification -->
        <section class="presentation-page" data-page="3" data-lesson="1.3">
            <div class="presentation-content">
                <div class="flex flex-col items-center h-full px-6 sm:px-8 py-12">
                    <div class="max-w-4xl w-full text-left">
                        <h2 class="text-4xl font-bold text-gray-900 mb-2">1.3 Parts Identification</h2>
                    <div class="h-1 w-24 bg-violet-500 mb-8"></div>
                    
                    <div class="space-y-10 flex-grow">
                        <!-- Pistol Parts -->
                        <div class="bg-violet-50 rounded-lg p-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-crosshairs text-violet-500"></i>
                                Pistol Components
                            </h3>
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div class="space-y-2">
                                    <p class="text-gray-700"><strong class="text-violet-600">Slide:</strong> The moving top portion that cycles back and forth</p>
                                    <p class="text-gray-700"><strong class="text-violet-600">Barrel:</strong> Rifled tube through which projectile travels</p>
                                    <p class="text-gray-700"><strong class="text-violet-600">Frame:</strong> Lower structural component holding internal mechanisms</p>
                                </div>
                                <div class="space-y-2">
                                    <p class="text-gray-700"><strong class="text-violet-600">Trigger:</strong> Lever that releases the firing mechanism</p>
                                    <p class="text-gray-700"><strong class="text-violet-600">Hammer:</strong> Component that strikes the firing pin</p>
                                    <p class="text-gray-700"><strong class="text-violet-600">Sights:</strong> Aiming devices on top of the slide</p>
                                </div>
                            </div>
                        </div>

                        <!-- Revolver Parts -->
                        <div class="bg-blue-50 rounded-lg p-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-sync-alt text-blue-500"></i>
                                Revolver Components
                            </h3>
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div class="space-y-2">
                                    <p class="text-gray-700"><strong class="text-blue-600">Cylinder:</strong> Rotating chamber holding ammunition</p>
                                    <p class="text-gray-700"><strong class="text-blue-600">Hammer:</strong> Cocked and released to fire each round</p>
                                    <p class="text-gray-700"><strong class="text-blue-600">Trigger:</strong> Controls hammer release and cylinder rotation</p>
                                </div>
                                <div class="space-y-2">
                                    <p class="text-gray-700"><strong class="text-blue-600">Frame:</strong> Main body structure</p>
                                    <p class="text-gray-700"><strong class="text-blue-600">Barrel:</strong> Fixed component through which projectile exits</p>
                                    <p class="text-gray-700"><strong class="text-blue-600">Crane:</strong> Mechanism that swings out to load cylinder</p>
                                </div>
                            </div>
                        </div>

                        <!-- Ammunition Systems -->
                        <div class="bg-amber-50 rounded-lg p-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-cubes text-amber-600"></i>
                                Ammunition Systems
                            </h3>
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <p class="font-semibold text-gray-800 mb-2">Magazine System (Pistols)</p>
                                    <ul class="space-y-2 text-gray-700">
                                        <li>• Detachable magazines hold ammunition</li>
                                        <li>• Spring-fed rounds move upward</li>
                                        <li>• Quick magazine changes possible</li>
                                        <li>• Typical capacity: 10-20+ rounds</li>
                                    </ul>
                                </div>
                                <div>
                                    <p class="font-semibold text-gray-800 mb-2">Cylinder System (Revolvers)</p>
                                    <ul class="space-y-2 text-gray-700">
                                        <li>• Fixed cylinder with chambers</li>
                                        <li>• Manual loading and unloading</li>
                                        <li>• Cylinder rotates for alignment</li>
                                        <li>• Typical capacity: 5-6 rounds</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        @forelse ($lessonPages as $page)
            <section class="presentation-page {{ $loop->first ? 'active' : '' }}" data-page="{{ $loop->index }}" data-lesson="{{ $page->lesson_index }}">
                <div class="presentation-content">
                    {!! $page->body_html !!}
                </div>
            </section>
        @empty
            <section class="presentation-page active" data-page="0" data-lesson="0">
                <div class="presentation-content">
                    <div class="card p-6">
                        <h3 class="presentation-title text-3xl mb-2">Lessons not available</h3>
                        <p class="text-sm text-gray-600">Please run the gun parts lesson migration to load the presentation content.</p>
                    </div>
                </div>
            </section>
        @endforelse
    </div>

    <div class="border-t border-violet-100 bg-white/90 px-6 sm:px-8 py-4">
        <div class="presentation-nav">
            <button type="button" id="presentation-prev" class="presentation-btn">
                <i class="fas fa-arrow-left text-sm"></i> Previous
            </button>
            <div class="presentation-dots" aria-label="Presentation pages">
                @php
                    $dotCount = max(1, $lessonPages->count());
                @endphp
                @for ($i = 0; $i < $dotCount; $i++)
                    <span class="presentation-dot {{ $i === 0 ? 'active' : '' }}" data-dot="{{ $i }}"></span>
                @endfor
            </div>
            <button type="button" id="presentation-next" class="presentation-btn">
                Next <i class="fas fa-arrow-right text-sm"></i>
            </button>
        </div>
    </div>
</div>