<div class="presentation-shell">
    <div class="bg-gradient-to-r from-violet-950 to-violet-800 text-white px-6 sm:px-8 py-5 flex items-center justify-between gap-4 flex-wrap">
        <div>
            <p class="presentation-kicker text-violet-200 text-xs">Presentation</p>
            <h2 class="presentation-title text-3xl sm:text-4xl text-white mt-1">{{ $lesson?->title ?? 'Marksmanship Subject Overview' }}</h2>
        </div>
        <div class="text-xs text-violet-100 max-w-md">
            Use the arrows to move page by page. Scrolling is disabled in this shell.
        </div>
    </div>

    <div class="presentation-stage" id="presentation-stage">
        @php
            $lessonPages = $lessonPages ?? collect();
        @endphp

        <!-- Introduction Page -->
        <section class="presentation-page active" data-page="0" data-lesson="intro">
            <div class="presentation-content">
                <div class="flex flex-col justify-center items-center h-full px-6 sm:px-8 py-12">
                    <div class="max-w-2xl mx-auto text-left">
                        <p class="text-violet-600 text-sm font-semibold uppercase tracking-wide mb-3">Introduction</p>
                        <h1 class="text-5xl sm:text-6xl font-bold text-gray-900 mb-6">Gun Parts & Systems</h1>
                        <p class="text-xl text-gray-700 mb-8 leading-relaxed">
                            A comprehensive guide to understanding firearm components, weapon types, and identification of critical gun parts used across different weapon systems.
                        </p>
                        <div class="flex flex-col gap-4">
                            <p class="text-lg text-gray-600">This course covers:</p>
                            <ul class="space-y-3">
                                <li class="flex gap-3 items-center">
                                    <i class="fas fa-check text-violet-500"></i>
                                    <span class="text-gray-700">Firearm overview and safety concepts</span>
                                </li>
                                <li class="flex gap-3 items-center">
                                    <i class="fas fa-check text-violet-500"></i>
                                    <span class="text-gray-700">Weapon types and their characteristics</span>
                                </li>
                                <li class="flex gap-3 items-center">
                                    <i class="fas fa-check text-violet-500"></i>
                                    <span class="text-gray-700">Parts identification and functionality</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Lesson 1.1: Firearm Overview -->
        <section class="presentation-page" data-page="1" data-lesson="1.1">
            <div class="presentation-content">
                <div class="flex flex-col items-center h-full px-6 sm:px-8 py-12">
                    <div class="max-w-4xl w-full text-left">
                        <h2 class="text-4xl font-bold text-gray-900 mb-2">1.1 Firearm Overview</h2>
                        <div class="h-1 w-24 bg-violet-500 mb-8"></div>
                        
                        <div class="space-y-8 flex-grow">
                        <div>
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-gun text-violet-500"></i>
                                What is a Firearm?
                            </h3>
                            <p class="text-lg text-gray-700 leading-relaxed">
                                A firearm is a device designed to propel projectiles through a barrel using the force generated by a controlled explosion. Modern firearms are precision instruments used in law enforcement, military, and civilian applications.
                            </p>
                        </div>

                        <div>
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-shield-alt text-violet-500"></i>
                                General Safety Concept Overview
                            </h3>
                            <ul class="text-lg text-gray-700 space-y-3">
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span>Always treat every firearm as if it were loaded</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span>Keep the muzzle pointed in a safe direction</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span>Keep your finger off the trigger until ready</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span>Be aware of your target and surroundings</span>
                                </li>
                            </ul>
                        </div>

                        <div>
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-layer-group text-violet-500"></i>
                                Firearm Classification Basics
                            </h3>
                            <ul class="text-lg text-gray-700 space-y-3">
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span><strong>Pistols:</strong> Handheld firearms designed for one or two-handed operation</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span><strong>Rifles:</strong> Long-barreled firearms designed for accuracy at distance</span>
                                </li>
                                <li class="flex gap-3">
                                    <span class="text-violet-500 font-bold">•</span>
                                    <span><strong>Shotguns:</strong> Large-caliber weapons designed for spread ammunition</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Lesson 1.2: Weapon Types in System -->
        <section class="presentation-page" data-page="2" data-lesson="1.2">
            <div class="presentation-content">
                <div class="flex flex-col items-center h-full px-6 sm:px-8 py-12">
                    <div class="max-w-4xl w-full text-left">
                        <h2 class="text-4xl font-bold text-gray-900 mb-2">1.2 Weapon Types in System</h2>
                        <div class="h-1 w-24 bg-violet-500 mb-8"></div>
                        
                        <div class="space-y-10 flex-grow">
                        <!-- 9mm Pistol -->
                        <div class="border-l-4 border-violet-500 pl-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-3">• 9mm Pistol</h3>
                            <ul class="space-y-2 text-gray-700">
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Semi-automatic operation concept:</strong> Fires one round per trigger pull, automatically chambers the next round</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Magazine-fed system:</strong> Ammunition stored in removable magazines, typically 15-17 rounds</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Common use in law enforcement:</strong> Standard duty weapon for most police departments</span>
                                </li>
                            </ul>
                        </div>

                        <!-- .45 Caliber Pistol -->
                        <div class="border-l-4 border-violet-500 pl-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-3">• .45 Caliber Pistol</h3>
                            <ul class="space-y-2 text-gray-700">
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Larger caliber impact concept:</strong> Larger projectile (11.43mm) delivers more stopping power</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Semi-automatic mechanism:</strong> Same operational principle as 9mm but with enhanced power</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Recoil difference vs 9mm:</strong> Noticeably higher recoil impulse requires experienced handling</span>
                                </li>
                            </ul>
                        </div>

                        <!-- .38 Revolver -->
                        <div class="border-l-4 border-violet-500 pl-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-3">• .38 Revolver</h3>
                            <ul class="space-y-2 text-gray-700">
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Cylinder-based firing system:</strong> Ammunition held in rotating cylinder with typically 5-6 chambers</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Revolving mechanism:</strong> Cylinder rotates with each trigger pull to align next round</span>
                                </li>
                                <li class="flex gap-3">
                                    <i class="fas fa-arrow-right text-violet-500 mt-1"></i>
                                    <span><strong>Simplicity and reliability:</strong> Fewer moving parts make it extremely dependable</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Lesson 1.3: Parts Identification -->
        <section class="presentation-page" data-page="3" data-lesson="1.3">
            <div class="presentation-content">
                <div class="flex flex-col items-center h-full px-6 sm:px-8 py-12">
                    <div class="max-w-4xl w-full text-left">
                        <h2 class="text-4xl font-bold text-gray-900 mb-2">1.3 Parts Identification</h2>
                    <div class="h-1 w-24 bg-violet-500 mb-8"></div>
                    
                    <div class="space-y-10 flex-grow">
                        <!-- Pistol Parts -->
                        <div class="bg-violet-50 rounded-lg p-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-crosshairs text-violet-500"></i>
                                Pistol Components
                            </h3>
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div class="space-y-2">
                                    <p class="text-gray-700"><strong class="text-violet-600">Slide:</strong> The moving top portion that cycles back and forth</p>
                                    <p class="text-gray-700"><strong class="text-violet-600">Barrel:</strong> Rifled tube through which projectile travels</p>
                                    <p class="text-gray-700"><strong class="text-violet-600">Frame:</strong> Lower structural component holding internal mechanisms</p>
                                </div>
                                <div class="space-y-2">
                                    <p class="text-gray-700"><strong class="text-violet-600">Trigger:</strong> Lever that releases the firing mechanism</p>
                                    <p class="text-gray-700"><strong class="text-violet-600">Hammer:</strong> Component that strikes the firing pin</p>
                                    <p class="text-gray-700"><strong class="text-violet-600">Sights:</strong> Aiming devices on top of the slide</p>
                                </div>
                            </div>
                        </div>

                        <!-- Revolver Parts -->
                        <div class="bg-blue-50 rounded-lg p-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-sync-alt text-blue-500"></i>
                                Revolver Components
                            </h3>
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div class="space-y-2">
                                    <p class="text-gray-700"><strong class="text-blue-600">Cylinder:</strong> Rotating chamber holding ammunition</p>
                                    <p class="text-gray-700"><strong class="text-blue-600">Hammer:</strong> Cocked and released to fire each round</p>
                                    <p class="text-gray-700"><strong class="text-blue-600">Trigger:</strong> Controls hammer release and cylinder rotation</p>
                                </div>
                                <div class="space-y-2">
                                    <p class="text-gray-700"><strong class="text-blue-600">Frame:</strong> Main body structure</p>
                                    <p class="text-gray-700"><strong class="text-blue-600">Barrel:</strong> Fixed component through which projectile exits</p>
                                    <p class="text-gray-700"><strong class="text-blue-600">Crane:</strong> Mechanism that swings out to load cylinder</p>
                                </div>
                            </div>
                        </div>

                        <!-- Ammunition Systems -->
                        <div class="bg-amber-50 rounded-lg p-6">
                            <h3 class="text-2xl font-semibold text-gray-800 mb-4 flex items-center gap-2">
                                <i class="fas fa-cubes text-amber-600"></i>
                                Ammunition Systems
                            </h3>
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <p class="font-semibold text-gray-800 mb-2">Magazine System (Pistols)</p>
                                    <ul class="space-y-2 text-gray-700">
                                        <li>• Detachable magazines hold ammunition</li>
                                        <li>• Spring-fed rounds move upward</li>
                                        <li>• Quick magazine changes possible</li>
                                        <li>• Typical capacity: 10-20+ rounds</li>
                                    </ul>
                                </div>
                                <div>
                                    <p class="font-semibold text-gray-800 mb-2">Cylinder System (Revolvers)</p>
                                    <ul class="space-y-2 text-gray-700">
                                        <li>• Fixed cylinder with chambers</li>
                                        <li>• Manual loading and unloading</li>
                                        <li>• Cylinder rotates for alignment</li>
                                        <li>• Typical capacity: 5-6 rounds</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        @forelse ($lessonPages as $page)
            <section class="presentation-page {{ $loop->first ? 'active' : '' }}" data-page="{{ $loop->index }}" data-lesson="{{ $page->lesson_index }}">
                <div class="presentation-content">
                    {!! $page->body_html !!}
                </div>
            </section>
        @empty
            <section class="presentation-page active" data-page="0" data-lesson="0">
                <div class="presentation-content">
                    <div class="card p-6">
                        <h3 class="presentation-title text-3xl mb-2">Lessons not available</h3>
                        <p class="text-sm text-gray-600">Please run the gun parts lesson migration to load the presentation content.</p>
                    </div>
                </div>
            </section>
        @endforelse

        <!-- Lesson 1.4: Assemble / Disassemble Trainer (always last page) -->
        <section class="presentation-page" data-page="999" data-lesson="1.4">
            <div class="presentation-content p-4 sm:p-6 overflow-auto">
                <div class="max-w-5xl mx-auto text-left mb-4">
                    <p class="text-violet-600 text-sm font-semibold uppercase tracking-wide mb-1">Hands-on Practice</p>
                    <h2 class="text-3xl sm:text-4xl font-bold text-gray-900 mb-2">1.4 Assemble &amp; Disassemble Trainer</h2>
                    <div class="h-1 w-24 bg-violet-500 mb-4"></div>
                    <p class="text-gray-600">Drag each part from the tray onto the pistol to assemble it layer by layer, or switch to Disassemble to remove the parts back into the tray.</p>
                </div>
                @include('Students.partials.assembly-simulator')
            </div>
        </section>
    </div>

    <div class="border-t border-violet-100 bg-white/90 px-6 sm:px-8 py-4">
        <div class="presentation-nav">
            <button type="button" id="presentation-prev" class="presentation-btn">
                <i class="fas fa-arrow-left text-sm"></i> Previous
            </button>
            <div class="presentation-dots" aria-label="Presentation pages">
                @php
                    $dotCount = max(1, $lessonPages->count());
                @endphp
                @for ($i = 0; $i < $dotCount; $i++)
                    <span class="presentation-dot {{ $i === 0 ? 'active' : '' }}" data-dot="{{ $i }}"></span>
                @endfor
            </div>
            <button type="button" id="presentation-next" class="presentation-btn">
                Next <i class="fas fa-arrow-right text-sm"></i>
            </button>
        </div>
    </div>

    <button type="button" id="la-toggle-btn" class="la-toggle-btn" aria-label="Toggle live activity panel">
        <i class="fas fa-users"></i>
        <span>Live</span>
        <span class="la-toggle-count" id="la-toggle-count">0</span>
    </button>

    <aside id="la-panel" class="la-panel" aria-label="Students currently in the lesson" aria-hidden="true">
        <div class="la-panel-header">
            <div>
                <p class="la-panel-kicker">Lesson activity</p>
                <h3 class="la-panel-title">Students currently opening the lesson</h3>
            </div>
            <button type="button" id="la-panel-close" class="la-panel-close" aria-label="Close panel">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <div class="la-panel-body">
            <div class="la-panel-meta">
                <span class="la-pulse-dot"></span>
                <span id="la-panel-meta-text">Refreshing every 5 seconds</span>
            </div>
            <div class="la-panel-tablewrap">
                <table class="la-panel-table">
                    <thead>
                        <tr>
                            <th>Student</th>
                            <th>Course / Year / Section</th>
                            <th>Page</th>
                        </tr>
                    </thead>
                    <tbody id="la-panel-tbody">
                        <tr id="la-panel-empty">
                            <td colspan="3" class="la-panel-empty">
                                <i class="fas fa-users-slash"></i>
                                <p>No other students are viewing right now.</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </aside>
</div>

<style>
    .la-toggle-btn{position:fixed;right:20px;bottom:20px;z-index:80;display:inline-flex;align-items:center;gap:8px;padding:10px 14px;border-radius:9999px;background:linear-gradient(135deg,#5B21B6,#7C3AED);color:#fff;font-weight:800;font-size:12px;box-shadow:0 14px 30px -10px rgba(91,33,182,.55),0 0 0 1px rgba(255,255,255,.08) inset;cursor:pointer;border:none;transition:transform .2s,box-shadow .2s}
    .la-toggle-btn:hover{transform:translateY(-2px);box-shadow:0 18px 36px -10px rgba(91,33,182,.7),0 0 0 1px rgba(255,255,255,.1) inset}
    .la-toggle-btn .la-toggle-count{display:inline-flex;align-items:center;justify-content:center;min-width:22px;height:22px;padding:0 6px;border-radius:9999px;background:#fff;color:#5B21B6;font-size:11px;font-weight:800;line-height:1}
    .la-pulse-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#22c55e;box-shadow:0 0 0 0 rgba(34,197,94,.6);animation:laPulse 1.8s infinite}
    @keyframes laPulse{0%{box-shadow:0 0 0 0 rgba(34,197,94,.6)}70%{box-shadow:0 0 0 10px rgba(34,197,94,0)}100%{box-shadow:0 0 0 0 rgba(34,197,94,0)}}
    .la-panel{position:fixed;top:0;right:0;height:100vh;width:340px;max-width:92vw;background:#fff;border-left:1px solid #ede9fe;box-shadow:-22px 0 50px -16px rgba(30,5,82,.25);transform:translateX(100%);transition:transform .3s cubic-bezier(.4,0,.2,1);z-index:90;display:flex;flex-direction:column}
    .la-panel.open{transform:translateX(0)}
    .la-panel-header{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:18px 18px 12px;border-bottom:1px solid #f3f4f6;background:linear-gradient(135deg,#faf5ff,#fff)}
    .la-panel-kicker{font-size:9px;letter-spacing:.28em;text-transform:uppercase;font-weight:800;color:#7c3aed;margin:0}
    .la-panel-title{font-family:'Space Grotesk',sans-serif;font-weight:800;font-size:14px;color:#111827;margin:4px 0 0;line-height:1.3}
    .la-panel-close{background:transparent;border:none;color:#6b7280;cursor:pointer;width:32px;height:32px;border-radius:8px;display:flex;align-items:center;justify-content:center;transition:background .15s,color .15s}
    .la-panel-close:hover{background:#f3f4f6;color:#111827}
    .la-panel-body{padding:14px 16px 18px;flex:1;overflow-y:auto;display:flex;flex-direction:column;gap:12px}
    .la-panel-meta{display:inline-flex;align-items:center;gap:8px;font-size:11px;color:#6b7280;background:#f9fafb;border:1px solid #f3f4f6;border-radius:9999px;padding:6px 10px;align-self:flex-start}
    .la-panel-tablewrap{flex:1;overflow:auto;border:1px solid #ede9fe;border-radius:12px;background:#fff}
    .la-panel-table{width:100%;border-collapse:separate;border-spacing:0;font-size:12px}
    .la-panel-table th{background:#faf5ff;font-size:9px;letter-spacing:.18em;text-transform:uppercase;font-weight:800;color:#5b21b6;padding:10px 12px;text-align:left;position:sticky;top:0;z-index:1}
    .la-panel-table td{padding:10px 12px;border-bottom:1px solid #f3f4f6;color:#1f2937;vertical-align:middle}
    .la-panel-table tbody tr:last-child td{border-bottom:none}
    .la-panel-table tbody tr:hover{background:#faf5ff}
    .la-panel-empty{text-align:center;color:#6b7280;padding:32px 16px !important}
    .la-panel-empty i{display:block;font-size:24px;color:#d1d5db;margin-bottom:8px}
    .la-panel-empty p{margin:0;font-size:12px}
    .la-panel-avatar{width:26px;height:26px;border-radius:50%;background:linear-gradient(135deg,#7c3aed,#5b21b6);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:9px;flex-shrink:0}
    .la-panel-name{font-weight:700;color:#111827;font-size:12px;line-height:1.2}
    .la-panel-id{color:#6b7280;font-size:10px;margin-top:1px}
    .la-panel-meta-line{color:#6b7280;font-size:10px;line-height:1.3}
    .la-panel-page{display:inline-flex;align-items:center;gap:4px;padding:2px 7px;border-radius:9999px;background:#ede9fe;color:#5b21b6;font-size:9px;font-weight:700}
    @media(max-width:480px){.la-toggle-btn span:not(.la-toggle-count){display:none}.la-toggle-btn{padding:12px 14px}}
</style>

<script>
    (function () {
        const lessonKey = 'gun-parts-presentation';
        const apiBase = @json(route('api.lesson.active-students')) + '?lesson=' + lessonKey;
        const heartbeatUrl = @json(route('api.lesson.heartbeat'));

        const toggleBtn = document.getElementById('la-toggle-btn');
        const panel = document.getElementById('la-panel');
        const panelClose = document.getElementById('la-panel-close');
        const tbody = document.getElementById('la-panel-tbody');
        const countBadge = document.getElementById('la-toggle-count');
        const metaText = document.getElementById('la-panel-meta-text');

        let pollTimer = null;
        let heartTimer = null;
        let inFlight = false;
        let isOpen = false;

        function getCurrentPage() {
            const active = document.querySelector('.presentation-page.active');
            if (!active) return 0;
            const idx = parseInt(active.dataset.page, 10);
            return Number.isNaN(idx) ? 0 : idx;
        }

        function escapeHtml(s) {
            if (s == null) return '';
            return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
        }

        function initials(first, last, full) {
            const f = (first || '').trim();
            const l = (last || '').trim();
            if (f || l) return (f.charAt(0) + l.charAt(0)).toUpperCase();
            const parts = (full || '?').split(/\s+/);
            return ((parts[0] || '?').charAt(0) + (parts[1] || '').charAt(0)).toUpperCase();
        }

        function render(rows) {
            countBadge.textContent = rows.length;
            if (rows.length === 0) {
                tbody.innerHTML = '<tr id="la-panel-empty"><td colspan="3" class="la-panel-empty"><i class="fas fa-users-slash"></i><p>No other students are viewing right now.</p></td></tr>';
                return;
            }
            tbody.innerHTML = rows.map(r => {
                const page = Math.max(1, (parseInt(r.current_page, 10) || 0) + 1);
                const init = initials(r.first_name, r.last_name, r.full_name);
                const meta = ((r.course || '—') + ' / ' + (r.year_level || '—') + ' / ' + (r.section || '—')).replace(/^[\s\/]+|[\s\/]+$/g, '');
                return '<tr>' +
                    '<td><div style="display:flex;align-items:center;gap:8px"><div class="la-panel-avatar">' + escapeHtml(init) + '</div><div><div class="la-panel-name">' + escapeHtml(r.full_name || '—') + '</div><div class="la-panel-id">' + escapeHtml(r.student_id) + '</div></div></div></td>' +
                    '<td><div class="la-panel-meta-line">' + escapeHtml(meta) + '</div></td>' +
                    '<td><span class="la-panel-page"><i class="fas fa-file-lines"></i> ' + page + '</span></td>' +
                '</tr>';
            }).join('');
        }

        async function fetchActive() {
            if (inFlight) return;
            inFlight = true;
            try {
                const res = await fetch(apiBase, { headers: { 'Accept': 'application/json' }, credentials: 'same-origin' });
                if (!res.ok) throw new Error('http ' + res.status);
                const data = await res.json();
                render(data.students || []);
                if (metaText) metaText.textContent = 'Updated just now · ' + (data.count || 0) + ' active';
            } catch (err) {
                console.error('Active students fetch failed', err);
            } finally {
                inFlight = false;
            }
        }

        async function sendHeartbeat() {
            try {
                await fetch(heartbeatUrl, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-CSRF-TOKEN': @json(csrf_token()) },
                    credentials: 'same-origin',
                    body: JSON.stringify({ lesson: lessonKey, current_page: getCurrentPage() })
                });
            } catch (err) {
                console.error('Heartbeat failed', err);
            }
        }

        function openPanel() {
            isOpen = true;
            panel.classList.add('open');
            panel.setAttribute('aria-hidden', 'false');
            fetchActive();
        }

        function closePanel() {
            isOpen = false;
            panel.classList.remove('open');
            panel.setAttribute('aria-hidden', 'true');
        }

        toggleBtn && toggleBtn.addEventListener('click', function () {
            if (isOpen) closePanel(); else openPanel();
        });
        panelClose && panelClose.addEventListener('click', closePanel);

        if (pollTimer) clearInterval(pollTimer);
        pollTimer = setInterval(() => { if (isOpen) fetchActive(); }, 5000);

        if (heartTimer) clearInterval(heartTimer);
        sendHeartbeat();
        heartTimer = setInterval(sendHeartbeat, 15000);

        document.addEventListener('keydown', function (e) {
            if (e.key === 'Escape' && isOpen) closePanel();
        });
    })();
</script>